// Code generated by goctl. DO NOT EDIT.
package types

type AddSongReq struct {
	Name            string `json:"name"`
	Address         string `json:"address"`
	SongListId      int    `json:"songListId"`
	PicctureAddress string `json:"pictureAddr"`
	PlatForm        string `json:"platform"`
	SignerId        string `json:"singerId"`
	Album           string `json:"album"`
	AlbumId         string `json:"albumId"`
}

type AddSongResp struct {
	Base
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CreateSonglistReq struct {
	UserId   int    `json:"userId"`
	Name     string `json:"name"`
	IsPublic string `json:"isPublic"`
	Avatar   string `json:"avatar"`
	Describe string `json:"describe"`
}

type CreateSonglistResp struct {
	Base
}

type DeleteSongReq struct {
	SongId int `json:"songId"`
}

type DeleteSongResp struct {
	Base
}

type DeleteSonglistReq struct {
	UserId     int `json:"userId"`
	SongListId int `json:"songListId"`
}

type DeleteSonglistResp struct {
	Base
}

type GetSongListReq struct {
	SonglistId int `json:"songlistId"`
}

type GetSongListResp struct {
	UserId   int    `json:"userId"`
	Name     string `json:"name"`
	IsPublic string `json:"isPublic"`
	Avatar   string `json:"avatar"`
	Describe string `json:"describe"`
}

type GetSongReq struct {
	SongId int `json:"songId"`
}

type GetSongResp struct {
	Name            string `json:"name"`
	Address         string `json:"address"`
	SongListId      int    `json:"songListId"`
	PicctureAddress string `json:"pictureAddr"`
	PlatForm        string `json:"platform"`
	SignerId        string `json:"singerId"`
	Album           string `json:"album"`
	AlbumId         string `json:"albumId"`
	CollectTime     int    `json:"collectTime"`
}

type GetUSerInfoReq struct {
	UserId int `path:"userId"`
}

type GetUSerInfoResp struct {
	Name            string `json:"name"`
	PhoneNunber     string `json:"phoneNumber"`
	Eamil           string `json:"email"`
	Avatar          string `json:"avatar"`
	StatusFlag      string `json:"statusFlag"`
	PersonSignature string `json:"personSignature"`
}

type ResetPasswordReq struct {
	UserId      int    `json:"userId"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ResetPasswordResp struct {
	Base
}

type UpdateSongListReq struct {
	UserId   int    `json:"userId"`
	Name     string `json:"name"`
	IsPublic string `json:"isPublic"`
	Avatar   string `json:"avatar"`
	Describe string `json:"describe"`
}

type UpdateSongListResp struct {
	Base
}

type UpdateSongReq struct {
	Name            string `json:"name"`
	Address         string `json:"address"`
	SongListId      int    `json:"songListId"`
	PicctureAddress string `json:"pictureAddr"`
	PlatForm        string `json:"platform"`
	SignerId        string `json:"singerId"`
	Album           string `json:"album"`
	AlbumId         string `json:"albumId"`
}

type UpdateSongResp struct {
	Base
}

type UpdateUserInfoReq struct {
	Name            string `json:"name"`
	PhoneNunber     string `json:"phoneNumber"`
	Eamil           string `json:"email"`
	Avatar          string `json:"avatar"`
	PersonSignature string `json:"personSignature"`
}

type UpdateUserInfoResp struct {
	Base
}

type UserLoginReq struct {
	UserId   int    `form:"userId"`
	Password string `form:"psaaword"`
}

type UserLoginResp struct {
	Token string `json:"token"`
	Base
}

type UserRegisterReq struct {
	UserId          int    `json:"userId"`
	Password        string `json:"password"`
	Name            string `json:"name"`
	PhoneNumber     string `json:"phoneNumber"`
	Eamil           string `json:"email"`
	Avatar          string `json:"avatar"`
	PersonSignature string `json:"personSignature"`
}

type UserRegisterResp struct {
	Base
}
