// Code generated by goctl. DO NOT EDIT.
package types

type AddSonglistReq struct {
	Name     string `json:"name"`
	Describe string `json:"describe"`
}

type AddSonglistResp struct {
	Base
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserLoginReq struct {
	Name     string `json:"name"`
	Password string `json:"psaaword"`
}

type UserLoginResp struct {
	Base
}
