// Code generated by goctl. DO NOT EDIT.

package songlist

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	songlistFieldNames          = builder.RawFieldNames(&Songlist{})
	songlistRows                = strings.Join(songlistFieldNames, ",")
	songlistRowsExpectAutoSet   = strings.Join(stringx.Remove(songlistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	songlistRowsWithPlaceHolder = strings.Join(stringx.Remove(songlistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	songlistModel interface {
		Insert(ctx context.Context, data *Songlist) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Songlist, error)
		Update(ctx context.Context, data *Songlist) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSonglistModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Songlist struct {
		Id           int64     `db:"id"`             // 歌单ID,主键
		OwnUserId    int64     `db:"own_user_id"`    // 歌单拥有者ID
		Name         string    `db:"name"`           // 歌单名称
		LastPlayTime time.Time `db:"last_play_time"` // 最后一次播放时间
		PlayCount    int64     `db:"play_count"`     // 播放次数
		IsPublic     int64     `db:"is_public"`      // 是否公开
		Avatar       string    `db:"avatar"`         // 歌曲头像，默认用最后一次收藏的歌曲图片
		Describe     string    `db:"describe"`       // 歌单描述
	}
)

func newSonglistModel(conn sqlx.SqlConn) *defaultSonglistModel {
	return &defaultSonglistModel{
		conn:  conn,
		table: "`songlist`",
	}
}

func (m *defaultSonglistModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSonglistModel) FindOne(ctx context.Context, id int64) (*Songlist, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", songlistRows, m.table)
	var resp Songlist
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSonglistModel) Insert(ctx context.Context, data *Songlist) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, songlistRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnUserId, data.Name, data.LastPlayTime, data.PlayCount, data.IsPublic, data.Avatar, data.Describe)
	return ret, err
}

func (m *defaultSonglistModel) Update(ctx context.Context, data *Songlist) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, songlistRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnUserId, data.Name, data.LastPlayTime, data.PlayCount, data.IsPublic, data.Avatar, data.Describe, data.Id)
	return err
}

func (m *defaultSonglistModel) tableName() string {
	return m.table
}
