// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	songlist "listen-server/app/user/cmd/api/user/internal/handler/songlist"
	user "listen-server/app/user/cmd/api/user/internal/handler/user"
	"listen-server/app/user/cmd/api/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/songlist/:user-id/add",
				Handler: songlist.AddSonglistHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
